### ISSUE TITLE
Still up to date?

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya-env-dev#15]
Are all of these packages really needed? What's e. g. the reason for `paypal/rest-api-sdk-php` or `stripe/stripe-php`?
I think these belong to `luya-module-payment`... Not sure about some others aswell...

Config should be checked aswell.
E. g. `publicOpenApi` in `admin` shouldn't be there I think.

**Comment by nadar** [comment]
The main idea behind those dependencies is to make it easier work with those modules. Those two packages are indeed dependencies from the LUYA Payment Module. Now if you "install" the LUYA Payment Module those deps already exists, otherwise you would have to extract them from the composer.json. Do you have any conflicts? I would keep them if possible.

Why could also turn off `publicOpenApi` by default, but to display those variables makes sense in a dev env i would say. Whats your intention?

**Comment by JohnnyMcWeed** [comment]
Everything seems to be working when installing. I am just asking because I wasn't sure about the reason behind it. But this makes sense 👍 

BTW: Shouldn't there be any crosses? https://i.imgur.com/Ny0twnE.png (It's working anyway)

**Comment by nadar** [comment]
Yes indeed, the code is here if you like to send a PR: https://github.com/luyadev/luya/blob/master/dev/RepoController.php#L121

**Comment by nadar** [comment]
So i am going to close this issue, if there is something we can do, let me know :-)
